### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [thewchan/jules-verne_michael-strogoff_w-h-g-kingston#1]
General Issues:

- [x] Some word changes do not sound alike: Tiflis → Tiblisi, Turkenstan → Turkestan, Moskowa → Moskva, telga → telega, Saisang → Zaysan, and Tartar → Tatar. These changes need to be reverted back.

chapter-2-2.xhtml:

- [x] You can remove italics from "en route".

chapter-2-3.xhtml:

- [ ] "Pardieu!" needs to be in italics and tagged as French.

chapter-2-4.xhtml:

- [x] "TOmst" and "Tomst" should be "Tomsk".

chapter-2-5.xhtml:

- [x] "en fête" needs to be tagged as French.

chapter-2-12.xhtml:

- [x] You can remove italics from "coup de main".

**Comment by thewchan** [comment]
Thanks @EmmaSweeney, I have made all changes except for `Pardieu`, which apparently is already in italics with language tag, can you check to make sure it shows up in your fork once pulled? 

Let me know if the edits are good to go. Thanks!
